name: Clone to HybridSDK

on:
  push:
    tags:
      - '*' # This workflow will trigger on any tag push

jobs:
  clone_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GithubActionTest repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for tags

      - name: Configure Git User
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Clone HybridSDK (using HTTPS with PAT) and Copy Content
        run: |
          # Clone HybridSDK to a temporary directory using the PAT for authentication
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/chandandevpulse/HybridSDK.git temp_hybrid_sdk

          # Change to the HybridSDK repository directory
          cd temp_hybrid_sdk

          # Checkout the develop branch. Create if it doesn't exist.
          git checkout develop || git checkout -b develop

          # --- START: Changes for new folder structure ---

          # Remove existing Frameworks/GithubActionTest directory to ensure a clean clone
          # This ensures that old files in this specific path are removed
          rm -rf Frameworks/GithubActionTest

          # Create the nested directory structure: Frameworks/GithubActionTest
          # -p flag ensures parent directories are created if they don't exist
          mkdir -p Frameworks/GithubActionTest

          # Copy contents from GithubActionTest into Frameworks/GithubActionTest
          # '../.' refers to the root of the GithubActionTest repo.
          # We copy its contents directly into the newly created target folder.
          rsync -av --exclude '.git' --exclude '.github' ../. Frameworks/GithubActionTest/

          # --- END: Changes for new folder structure ---

          # Add changes
          # We add the Frameworks folder to stage all changes within it
          git add Frameworks

          # Commit changes if there are any
          git diff --quiet --exit-code --cached || git commit -m "Automated: Clone GithubActionTest tag ${{ github.ref_name }} into Frameworks/GithubActionTest"

          # Push to the develop branch of HybridSDK
          git push origin develop
        working-directory: ${{ github.workspace }}

      - name: Clean up temporary HybridSDK folder
        run: rm -rf temp_hybrid_sdk
        working-directory: ${{ github.workspace }} # Ensure we are in the root of GithubActionTest repo. check once
